### ISSUE TITLE
Please Stop Using My Firebase Credentials

### ISSUE THREAD

**Issue by aman-janwani** [nebuchad-nezzar/Ecommerce#1]

**Comment by nebuchad-nezzar** [comment]
Hi...Its not yours please check. I'm using mine alone.
Thanks

**Comment by aman-janwani** [comment]
In Permissions.js file
![Screenshot_20220920-215030_Chrome](https://user-images.githubusercontent.com/69379499/191311918-94cc6152-c94c-4cf6-b7a7-b675867a337a.jpg)

**Comment by nebuchad-nezzar** [comment]
please check
